### ISSUE TITLE
Did this work?

### ISSUE THREAD

**Issue by BransonGitomeh** [lethiandev/heroku-buildpack-godot#1]
Hey developer, i was hoping to get started with a heroku buildpack to automate html5 deployment and if possible other builds and uploads. How far did you go with this? are you using it in any way? 

thanks.

**Comment by tanjunior** [comment]
manged to get it compiling and exporting as html5

**Comment by BransonGitomeh** [comment]
nice, thanks.

**Comment by BransonGitomeh** [comment]
maybe we can make it host the html files built? or all the builds that are produced? that would save many devs alot of time

**Comment by lethiandev** [comment]
Hi, I've used this buildpack for my Godot experimental projects, should work fine but requires some preparation first - only HTML5 preset called "HTML5" is supported as the name is hard-coded in the build script. Unfortunately other platforms are currently not supported as the buildpack's purpose is to build and run the web app directly on Heroku's servers.

**Comment by tanjunior** [comment]
Does this work for hosting an ENET server?

**Comment by lethiandev** [comment]
Web app is simply served by using Python's SimpleHTTPServer module, but this buildpack doesn't work with custom ENet servers. Anyway should be easy to achieve this following [official docs](https://docs.godotengine.org/en/stable/getting_started/workflow/export/exporting_for_dedicated_servers.html) and using server built Godot instead of the headless one, or use both for building pkg file ([--export "Target" game_data.pck](https://docs.godotengine.org/en/stable/getting_started/workflow/export/exporting_projects.html#exporting-from-the-command-line)) and run the project using the server binary.

**Comment by tanjunior** [comment]
like this? https://github.com/tanjunior/heroku-buildpack-godot/tree/server

**Comment by tanjunior** [comment]
I think there is a bug with exporting as Linux/11, the export template does not work

**Comment by lethiandev** [comment]
Looks ok to me, but I'd consider running the server in `bin/release` script instead of the compile as described on Heroku [docs](https://devcenter.heroku.com/articles/buildpack-api#bin-release).

**Comment by tanjunior** [comment]
I never could really understand dynos on heroku.
will this work?
`web: cd $CACHE_DIR/ && godot_server.64 --main-pack "$OUTPUT_DEST/game_data.pck"`

**Comment by lethiandev** [comment]
It may work, but if you don't bind to the Heroku's supplied PORT (env variable), then the app probably will just close. Also the PORT, I believe, just "forwards" the ports 80 and 443 to allow making response to HTTP requests but blocks other inbound traffic. Please refer to the Heroku's docs for more info. I'm closing the issue now because it become a bit of an offtop 🙂
